=== tomGru55/otvRac/lab3/schema.json
{
    "$id": "https://github.com/tomGru55/otvRac/blob/main/lab2/oscarsJSON.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "number",
                "description": "generirani id zapisa"
            },
            "naziv_ceremonije": {
                "type": "string",
                "description": "naziv ceremonije oscar"
            },
            "datum_ceremonije": {
                "type": "string",
                "format": "date",
                "description": "datum ceremonije Oscar"
            },
            "lokacija_ceremonije": {
                "type": "string",
                "description": "mjesto održavanja ceremonije Oscar"
            },
            "nagrade": {
                "type": "object",
                "properties": {
                    "kategorija_nagrade": {
                        "type": "string",
                        "description": "kategorija može biti: Najbolji glumac, Njabolji sporedni glumac, Najbolja glumica, Najbolja sporedna glumica"
                    },
                    "film": {
                        "type": "string",
                        "description": "ime filma za koji je dobitnik nagrađen"
                    },
                    "dobitnik_ime": {
                        "type": "string",
                        "description": "ime dobitnika nagrade Oscar"
                    },
                    "dobitnik_prezime": {
                        "type": "string",
                        "description": "prezime dobitnika nagrade Oscar"
                    },
                    "dobitnik_datumrod": {
                        "type": "string",
                        "format": "date",
                        "description": "\tdatum rođenja dobitnika nagrade Oscar"
                    },
                    "ime_lika_u_filmu": {
                        "type": "string",
                        "description": "\time lika u filmu kojeg je dobitnik nagrade portretirao"
                    },
                    "redatelj": {
                        "type": "string",
                        "description": "redatelj filma za koji je dobitnik nagrađen"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "kategorija_nagrade",
                    "film",
                    "dobitnik_ime",
                    "dobitnik_prezime",
                    "dobitnik_datumrod",
                    "ime_lika_u_filmu",
                    "redatelj"
                ],
                "description": "skup dodijeljenih nagrada na određenoj ceremoniji, na svakoj ceremoniji se dodjeljuje 4 nagrada"
            }
        },
        "required": [
            "naziv_ceremonije",
            "datum_ceremonije",
            "lokacija_ceremonije",
            "nagrade"
        ],
        "additionalProperties": false
    },
    "title": "Oscars Open Data",
    "description": "otvoreni skup podataka koji sadrži podatke o dodjelama nagrade oscar za glumu na ceremonijama oscar"
}

=== tomGru55/otvRac/lab2/OscarsOpenData/src/main/resources/static/oscarsJSON.json
[ {
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji glumac",
    "film" : "Mystic River",
    "dobitnik_ime" : "Sean",
    "dobitnik_prezime" : "Penn",
    "dobitnik_datumrod" : "1960-08-17",
    "ime_lika_u_filmu" : "Jimmy Markum",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji sporedni glumac",
    "film" : "Mystic River",
    "dobitnik_ime" : "Tim",
    "dobitnik_prezime" : "Robbins",
    "dobitnik_datumrod" : "1958-10-16",
    "ime_lika_u_filmu" : "Dave Boyle",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja glumica",
    "film" : "Monster",
    "dobitnik_ime" : "Charlize",
    "dobitnik_prezime" : "Theron",
    "dobitnik_datumrod" : "1975-08-07",
    "ime_lika_u_filmu" : "Alien Wuornos",
    "redatelj" : "Patty Jenkins"
  }
}, {
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja sporedna glumica",
    "film" : "Cold mountain",
    "dobitnik_ime" : "Ren√©e ",
    "dobitnik_prezime" : "Zellweger ",
    "dobitnik_datumrod" : "1969-04-25",
    "ime_lika_u_filmu" : "Ruby Thewes",
    "redatelj" : "Anthony Minghella"
  }
}, {
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji glumac",
    "film" : "Ray",
    "dobitnik_ime" : "Jamie",
    "dobitnik_prezime" : "Fox",
    "dobitnik_datumrod" : "1967-12-13",
    "ime_lika_u_filmu" : "Ray Charles",
    "redatelj" : "Taylor Hackford"
  }
}, {
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji sporedni glumac",
    "film" : "Million Dollar Baby",
    "dobitnik_ime" : "Morgan",
    "dobitnik_prezime" : "Freeman",
    "dobitnik_datumrod" : "1937-06-01",
    "ime_lika_u_filmu" : "Eddie Scrap-Iron Duprist",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja glumica",
    "film" : "Million Dollar Baby",
    "dobitnik_ime" : "Hillary",
    "dobitnik_prezime" : "Swank",
    "dobitnik_datumrod" : "1974-06-30",
    "ime_lika_u_filmu" : "Margaret Maggie Fitzgerald",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja sporedna glumica",
    "film" : "The Aviator",
    "dobitnik_ime" : "Cate",
    "dobitnik_prezime" : "Blanchett",
    "dobitnik_datumrod" : "1969-05-14",
    "ime_lika_u_filmu" : "Katherine Hepburn",
    "redatelj" : "Martin Scorsese"
  }
}, {
  "naziv_ceremonije" : "78th Academy awards",
  "datum_ceremonije" : "2006-04-05",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji glumac",
    "film" : "Capote",
    "dobitnik_ime" : "Phillip Seymour",
    "dobitnik_prezime" : "Hoffman",
    "dobitnik_datumrod" : "1967-06-23",
    "ime_lika_u_filmu" : "Truman Capote",
    "redatelj" : "Bennet Miller"
  }
}, {
  "naziv_ceremonije" : "78th Academy awards",
  "datum_ceremonije" : "2006-04-05",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji sporedni glumac",
    "film" : "Syriana",
    "dobitnik_ime" : "George",
    "dobitnik_prezime" : "Clooney",
    "dobitnik_datumrod" : "1961-05-06",
    "ime_lika_u_filmu" : "Bob Barnest",
    "redatelj" : "Stephen Gaghan"
  }
}, {
  "naziv_ceremonije" : "78th Academy awards",
  "datum_ceremonije" : "2006-04-05",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja glumica",
    "film" : "Walk the line",
    "dobitnik_ime" : "Reese",
    "dobitnik_prezime" : "Whiterspoon",
    "dobitnik_datumrod" : "1976-04-22",
    "ime_lika_u_filmu" : "June Carter Cash",
    "redatelj" : "James Mangold"
  }
}, {
  "naziv_ceremonije" : "78th Academy awards",
  "datum_ceremonije" : "2006-04-05",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja sporedna glumica",
    "film" : "The Constant Gardener",
    "dobitnik_ime" : "Rachel",
    "dobitnik_prezime" : "Weisz",
    "dobitnik_datumrod" : "1970-04-07",
    "ime_lika_u_filmu" : "Tessa Quayle",
    "redatelj" : "Fernando Meirelles"
  }
} ]

=== tomGru55/otvRac/lab4/OscarsOpenData/src/main/resources/static/oscarsJSON.json
[ {
  "id" : 1,
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji glumac",
    "film" : "Mystic River",
    "dobitnik_ime" : "Sean",
    "dobitnik_prezime" : "Penn",
    "dobitnik_datumrod" : "1960-08-17",
    "ime_lika_u_filmu" : "Jimmy Markum",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "id" : 2,
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji sporedni glumac",
    "film" : "Mystic River",
    "dobitnik_ime" : "Tim",
    "dobitnik_prezime" : "Robbins",
    "dobitnik_datumrod" : "1958-10-16",
    "ime_lika_u_filmu" : "Dave Boyle",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "id" : 3,
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja glumica",
    "film" : "Monster",
    "dobitnik_ime" : "Charlize",
    "dobitnik_prezime" : "Theron",
    "dobitnik_datumrod" : "1975-08-07",
    "ime_lika_u_filmu" : "Alien Wuornos",
    "redatelj" : "Patty Jenkins"
  }
}, {
  "id" : 4,
  "naziv_ceremonije" : "76th Academy awards",
  "datum_ceremonije" : "2004-02-29",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja sporedna glumica",
    "film" : "Cold mountain",
    "dobitnik_ime" : "Ren√©e ",
    "dobitnik_prezime" : "Zellweger ",
    "dobitnik_datumrod" : "1969-04-25",
    "ime_lika_u_filmu" : "Ruby Thewes",
    "redatelj" : "Anthony Minghella"
  }
}, {
  "id" : 5,
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji glumac",
    "film" : "Ray",
    "dobitnik_ime" : "Jamie",
    "dobitnik_prezime" : "Fox",
    "dobitnik_datumrod" : "1967-12-13",
    "ime_lika_u_filmu" : "Ray Charles",
    "redatelj" : "Taylor Hackford"
  }
}, {
  "id" : 6,
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji sporedni glumac",
    "film" : "Million Dollar Baby",
    "dobitnik_ime" : "Morgan",
    "dobitnik_prezime" : "Freeman",
    "dobitnik_datumrod" : "1937-06-01",
    "ime_lika_u_filmu" : "Eddie Scrap-Iron Duprist",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "id" : 7,
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja glumica",
    "film" : "Million Dollar Baby",
    "dobitnik_ime" : "Hillary",
    "dobitnik_prezime" : "Swank",
    "dobitnik_datumrod" : "1974-06-30",
    "ime_lika_u_filmu" : "Margaret Maggie Fitzgerald",
    "redatelj" : "Clint Eastwood"
  }
}, {
  "id" : 8,
  "naziv_ceremonije" : "77th Academy awards",
  "datum_ceremonije" : "2005-02-27",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja sporedna glumica",
    "film" : "The Aviator",
    "dobitnik_ime" : "Cate",
    "dobitnik_prezime" : "Blanchett",
    "dobitnik_datumrod" : "1969-05-14",
    "ime_lika_u_filmu" : "Katherine Hepburn",
    "redatelj" : "Martin Scorsese"
  }
}, {
  "id" : 9,
  "naziv_ceremonije" : "78th Academy awards",
  "datum_ceremonije" : "2006-04-05",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji glumac",
    "film" : "Capote",
    "dobitnik_ime" : "Phillip Seymour",
    "dobitnik_prezime" : "Hoffman",
    "dobitnik_datumrod" : "1967-06-23",
    "ime_lika_u_filmu" : "Truman Capote",
    "redatelj" : "Bennet Miller"
  }
}, {
  "id" : 10,
  "naziv_ceremonije" : "78th Academy awards",
  "datum_ceremonije" : "2006-04-05",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolji sporedni glumac",
    "film" : "Syriana",
    "dobitnik_ime" : "George",
    "dobitnik_prezime" : "Clooney",
    "dobitnik_datumrod" : "1961-05-06",
    "ime_lika_u_filmu" : "Bob Barnest",
    "redatelj" : "Stephen Gaghan"
  }
}, {
  "id" : 11,
  "naziv_ceremonije" : "78th Academy awards",
  "datum_ceremonije" : "2006-04-05",
  "lokacija_ceremonije" : "Kodak theatre, Los Angeles",
  "nagrade" : {
    "kategorija_nagrade" : "Najbolja glumica",
    "film" : "Walk the line",
    "dobitnik_ime" : "Reese",
    "dobitnik_prezime" : "Whiterspoon",
    "dobitnik_datumrod" : "1976-04-22",
    "ime_lika_u_filmu" : "June Carter Cash",
    "redatelj" : "James Mangold"
  }
} ]
